apiVersion: v1
kind: Service
metadata:
  name: myapp-service-nodeport

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30004 #30000 - 32767 range allowed
  selector:
    app: myapp